### ISSUE TITLE
no audio callback defined.

### ISSUE THREAD

**Issue by jamesstaub** [giuliomoro/tiles#1]
For some reason when I run this project I get the errors:

`Error: no audio callback defined. Make sure you set settings->render to point to your audio` `callbackError: unable to initialise audio`

it only started appearing after I uploaded the latest bela update patch. prior to the update I was able to run this program. 

I saw in the Bela source that this error could occur if you attempt to run more than one project at a time, but I don't get the error from any other projects.

 Any idea what may be causing the problem?

**Comment by giuliomoro** [comment]
Thanks, there were a few minor updates in the Bela API since then. Small, but still enough to break the code. I fixed it now. Let me know if you still have problems

**Comment by jamesstaub** [comment]
yes that worked, thank you!
